### PR TITLE
Fix player dragging issues

### PR DESCRIPTION
**Pull request by harish-aka-shivi**
*Description of changes:*
- Disable dragging when the cursor on video player.
- Increase the Toolbar height to give more dragging area and a buffer for drag cancel
- Add a border on player
- Increase little height to compensate for the player.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by harish-aka-shivi** [comment]
I would like to suggest to show the player on the bottom right corner.
My logic:
- When the user moves from the Main Stage to Networking Area, he does not want to focus on the presentation. Keeping the player at the top(which is the area the user first focusses), he would mostly try to drag.
- Most of the PIP player(YT) shows the player on the bottom right corner. This will keep our interface consistent with major platforms

**Comment by harish-aka-shivi** [comment]
Right now we are having issues when someone start dragging just after coming to the networking area. This is because the YT player is initializing and taking a lot of processing. So when we start dragging at that time, there is a visible lag. After some time it is a lot better.
I think we can try lazy initialization to fix that.

**Comment by joaoaguiam** [comment]
Regarding the bottom right, initially it was there, however if you have a call running, the player is on top of the jitsi menu/buttons. That’s why I moved to the top. We can though put on the left side inside the presence list. But I would suggest to keep like this at the top right and evaluate the best place with the new layout? What do you think?

**Comment by harish-aka-shivi** [comment]
Yeah, I agree we can think the position of the player with the new layout

**Pull request merged**
